title: Blog of diqbpow3c
description: A simple blog site of diqbpow3c.
theme: just-the-docs

url: https://diqbpow3c.github.io
heading_anchors: true
heading_numbering: true

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap
  - jekyll-feed

just_the_docs:
  collections:
    docs:
      name: docs

aux_links:
  "GitHub":
    - "https://github.com/diqbpow3c"
  "RSS/Atom Feed":
    - "/feed/docs.xml"

collections:
  docs:
    output: true

feed:
  collections:
    docs:
      path: "/feed/docs.xml"