title: diqbpow3c's Blog
description: A simple blog site.
theme: just-the-docs

url: https://diqbpow3c.github.io
heading_anchors: true
heading_numbering: true

plugins:
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap